---
name: Update Docker README

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  update-readme:
    name: Update Docker Hub README
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Sync README
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          slug: siphalor/extended-pandoc
          description: true
